
import type { Language } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  pt: {
    appName: "Gerador de Carrosséis IA",
    appDescription: "Gere carrosséis infinitos para o Instagram com um clique.",
    generateWithIA: "Gerar com IA",
    generateWithCSV: "Upload CSV",
    niche: "Nicho",
    nichePlaceholder: "Ex: finanças, fitness, fé cristã",
    context: "Contexto/Objetivo",
    contextPlaceholder: "Ex: frases de impacto para motivar",
    tone: "Tom das Frases",
    tonePlaceholder: "Ex: inspirador, provocativo, educativo",
    slidesCount: "Quantidade de Imagens/Frases",
    carouselsCount: "Quantidade de Carrosséis",
    backgroundStyle: "Estilo de Fundo",
    colorPalette: "Paleta de Cores",
    typography: "Estilo de Tipografia",
    phrasesLanguage: "Idioma das Frases",
    cta: "CTA no Último Slide?",
    yes: "Sim",
    no: "Não",
    ctaType: "Tipo de CTA",
    generate: "Gerar Conteúdo",
    generating: "Gerando...",
    uploadCsvInstruction: "Use um CSV com as colunas: carrossel_id, ordem_slide, frase",
    uploadFile: "Escolher Arquivo",
    orDrag: "ou arraste e solte aqui",
    fileSelected: "Arquivo selecionado:",
    resultsTitle: "Resultados Gerados",
    noResults: "Ainda não há resultados. Preencha o formulário e clique em gerar.",
    downloadJson: "Baixar JSON",
    downloadZip: "Baixar ZIP",
    downloadingZip: "Gerando ZIP...",
    footerText: "Selecione o modo, preencha as opções e clique em 'Gerar' para criar seus carrosséis. As imagens não são geradas, apenas os prompts para você usar em sua ferramenta de IA favorita.",
    errorTitle: "Ocorreu um erro",
    errorCheckConsole: "Verifique o console para mais detalhes.",
  },
  en: {
    appName: "AI Carousel Generator",
    appDescription: "Generate infinite carousels for Instagram with one click.",
    generateWithIA: "Generate with AI",
    generateWithCSV: "Upload CSV",
    niche: "Niche",
    nichePlaceholder: "E.g.: finance, fitness, christian faith",
    context: "Context/Objective",
    contextPlaceholder: "E.g.: impactful phrases to motivate",
    tone: "Tone of Phrases",
    tonePlaceholder: "E.g.: inspiring, provocative, educational",
    slidesCount: "Number of Images/Phrases",
    carouselsCount: "Number of Carousels",
    backgroundStyle: "Background Style",
    colorPalette: "Color Palette",
    typography: "Typography Style",
    phrasesLanguage: "Language of Phrases",
    cta: "CTA on Last Slide?",
    yes: "Yes",
    no: "No",
    ctaType: "CTA Type",
    generate: "Generate Content",
    generating: "Generating...",
    uploadCsvInstruction: "Use a CSV with columns: carrossel_id, ordem_slide, frase",
    uploadFile: "Choose File",
    orDrag: "or drag and drop here",
    fileSelected: "File selected:",
    resultsTitle: "Generated Results",
    noResults: "No results yet. Fill out the form and click generate.",
    downloadJson: "Download JSON",
    downloadZip: "Download ZIP",
    downloadingZip: "Generating ZIP...",
    footerText: "Select the mode, fill in the options, and click 'Generate' to create your carousels. The images are not generated, only the prompts for you to use in your favorite AI tool.",
    errorTitle: "An error occurred",
    errorCheckConsole: "Check the console for more details.",
  },
  es: {
    appName: "Generador de Carruseles IA",
    appDescription: "Genera carruseles infinitos para Instagram con un solo clic.",
    generateWithIA: "Generar con IA",
    generateWithCSV: "Subir CSV",
    niche: "Nicho",
    nichePlaceholder: "Ej: finanzas, fitness, fe cristiana",
    context: "Contexto/Objetivo",
    contextPlaceholder: "Ej: frases de impacto para motivar",
    tone: "Tono de las Frases",
    tonePlaceholder: "Ej: inspirador, provocador, educativo",
    slidesCount: "Cantidad de Imágenes/Frases",
    carouselsCount: "Cantidad de Carruseles",
    backgroundStyle: "Estilo de Fondo",
    colorPalette: "Paleta de Colores",
    typography: "Estilo de Tipografía",
    phrasesLanguage: "Idioma de las Frases",
    cta: "¿CTA en la Última Diapositiva?",
    yes: "Sí",
    no: "No",
    ctaType: "Tipo de CTA",
    generate: "Generar Contenido",
    generating: "Generando...",
    uploadCsvInstruction: "Usa un CSV con las columnas: carrossel_id, ordem_slide, frase",
    uploadFile: "Seleccionar Archivo",
    orDrag: "o arrastra y suelta aquí",
    fileSelected: "Archivo seleccionado:",
    resultsTitle: "Resultados Generados",
    noResults: "Aún no hay resultados. Completa el formulario y haz clic en generar.",
    downloadJson: "Descargar JSON",
    downloadZip: "Descargar ZIP",
    downloadingZip: "Generando ZIP...",
    footerText: "Selecciona el modo, completa las opciones y haz clic en 'Generar' para crear tus carruseles. Las imágenes no se generan, solo los prompts para que los uses en tu herramienta de IA favorita.",
    errorTitle: "Ocurrió un error",
    errorCheckConsole: "Revisa la consola para más detalles.",
  },
};

const TYPOGRAPHY_OPTIONS = {
  pt: [
    { name: 'Sans-serif moderna', value: 'Sans-serif moderna', fontFamily: "'Montserrat', sans-serif" },
    { name: 'Serif elegante', value: 'Serif elegante', fontFamily: "'Lora', serif" },
    { name: 'Script manuscrita', value: 'Script manuscrita', fontFamily: "'Dancing Script', cursive" },
    { name: 'Caixa alta bold', value: 'Caixa alta bold', fontFamily: "'Anton', sans-serif" },
  ],
  en: [
    { name: 'Modern sans-serif', value: 'Modern sans-serif', fontFamily: "'Montserrat', sans-serif" },
    { name: 'Elegant serif', value: 'Elegant serif', fontFamily: "'Lora', serif" },
    { name: 'Handwritten script', value: 'Handwritten script', fontFamily: "'Dancing Script', cursive" },
    { name: 'Uppercase bold', value: 'Uppercase bold', fontFamily: "'Anton', sans-serif" },
  ],
  es: [
    { name: 'Sans-serif moderna', value: 'Sans-serif moderna', fontFamily: "'Montserrat', sans-serif" },
    { name: 'Serif elegante', value: 'Serif elegante', fontFamily: "'Lora', serif" },
    { name: 'Script manuscrita', value: 'Script manuscrita', fontFamily: "'Dancing Script', cursive" },
    { name: 'Mayúsculas en negrita', value: 'Mayúsculas en negrita', fontFamily: "'Anton', sans-serif" },
  ],
};


export const STYLE_OPTIONS = {
  background: {
    pt: ['Fundo sólido minimalista', 'Degradê suave', 'Fundo com textura leve', 'Fundo com foto em baixa opacidade', 'Fundo "dark"'],
    en: ['Minimalist solid background', 'Soft gradient', 'Light texture background', 'Photo background with low opacity', '"Dark" background'],
    es: ['Fondo sólido minimalista', 'Degradado suave', 'Fondo con textura ligera', 'Fondo de foto con baja opacidad', 'Fondo "oscuro"'],
  },
  palette: {
    pt: ['Claro (tons pastéis)', 'Escuro (tons sóbrios)', 'Vibrante (cores fortes)', 'Neutro (preto, branco, cinza)'],
    en: ['Light (pastel tones)', 'Dark (sober tones)', 'Vibrant (strong colors)', 'Neutral (black, white, gray)'],
    es: ['Claro (tonos pastel)', 'Oscuro (tonos sobrios)', 'Vibrante (colores fuertes)', 'Neutro (negro, blanco, gris)'],
  },
  typography: TYPOGRAPHY_OPTIONS,
  ctaType: {
    pt: ['Seguir página', 'Salvar post', 'Comentar', 'Clicar no link da bio'],
    en: ['Follow page', 'Save post', 'Comment', 'Click link in bio'],
    es: ['Seguir página', 'Guardar publicación', 'Comentar', 'Hacer clic en el enlace de la bio'],
  }
};